[package]
name = "learn-rust-concurrent"
version = "0.1.0"
authors = ["whiteCcinn <471113744@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
